In [21]:
import pandas as pd

from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
)

In [22]:
train = pd.read_csv("../data/processed/train_clean.csv")
test = pd.read_csv("../data/processed/test_clean.csv")
train.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Customer Status,Last Due Date,Last Payment Date,Churn
0,160831,34,Male,32.0,26,0.0,17,Basic,Quarterly,890.21,30.0,active,1900-06-21,1900-07-08,0
1,354435,30,Male,36.0,22,0.0,15,Basic,Annual,954.37,30.0,active,1900-06-10,1900-06-25,0
2,444576,23,Male,44.0,14,0.0,24,Premium,Annual,674.00,21.0,inactive,1900-06-27,1900-07-21,1
3,130847,24,Male,39.0,21,2.0,14,Standard,Quarterly,775.00,18.0,active,1900-06-30,1900-07-14,0
4,108121,26,Male,32.0,26,1.0,5,Basic,Quarterly,679.45,0.0,active,1900-06-29,1900-07-04,0

In [23]:
baseline_features = [
    "Total Spend",
    "Usage Frequency",
    "Support Calls",
]

X = train[baseline_features]
y = train["Churn"]

In [24]:
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1234,
    stratify=y
)

In [25]:
model = DummyClassifier(strategy="constant", constant=0)
model.fit(X_train, y_train)

DummyClassifier(constant=0, strategy='constant')

In [26]:
y_pred_val = model.predict(X_val)
y_proba_val = model.predict_proba(X_val)[:, 1]

In [27]:
dumb_model = DummyClassifier(strategy="constant", constant=0)
dumb_model.fit(X_train, y_train)

y_pred = dumb_model.predict(X_val)

In [28]:
print("Accuracy:")
print(accuracy_score(y_val, y_pred))
print()
print("Confusion matrix:")
print(confusion_matrix(y_val, y_pred))
print()
print("AUC:")
print(roc_auc_score(y_val, y_proba_val))
# print("Classification report:") #outputs a warning
# print(classification_report(y_val, y_pred))

Accuracy:
0.7000082474226804

Confusion matrix:
[[42438     0]
 [18187     0]]

AUC:
0.5

In [29]:
X_test = test[baseline_features]
test_pred = model.predict(X_test)

submission = pd.DataFrame({
    "CustomerID": test["CustomerID"],
    "Churn": test_pred
})

submission.to_csv("../data/submissions/dumb_baseline.csv", index=False)
submission.head()

   CustomerID  Churn
0      262106      0
1       37061      0
2      361832      0
3      425516      0
4       60597      0